development:
  adapter: postgresql
  encoding: unicode
  database: RecipeCapstone_development
  pool: 5
  host: localhost
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: RecipeCapstone_test
  pool: 5
  host: localhost
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: recipe_production
  username: recipe
  password: <%= ENV["RECIPE_DATABASE_PASSWORD"] %>