development:
  adapter: postgresql
  encoding: unicode
  database: recipe_development
  pool: 5
  host: localhost
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: recipe_test
  pool: 5
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: recipe_production
  pool: 5
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>

staging:
  url: <%= ENV['DATABASE_URL'] %>